name: CI

on: [push]

jobs:
  ci-test:
    name: Test application
    runs-on: ubuntu-20.04
    steps:
      - name: Login in to Docker HUB
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
